name: Build, Test and Deploy Rules
permissions:
  contents: write
on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@master
      - name: Install Dependencies
        run: sudo apt-get install -y nodejs jsonlint
      - name: Build
        run: |
          mkdir public
          cp CNAME public/CNAME
          cp data.min.json public/data.min.json
          sha256sum public/data.min.json | awk '{print $1}' > public/rules.min.hash
          node build_tools/minifyDataJSON.js "public/data.min.json" "public/data.minify.json"
          sha256sum public/data.minify.json | awk '{print $1}' > public/rules.minify.hash
      - name: Upload Rules Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: rules-artifact
          path: public
  test:
    name: Test
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout Code
        uses: actions/checkout@master
      - name: Install Dependencies
        run: sudo apt-get install -y nodejs jsonlint
      - name: Download Rules Artifacts
        uses: actions/download-artifact@v4
        with:
          name: rules-artifact
          path: public
      - name: Test
        run: |
          jsonlint-php public/data.min.json
          jsonlint-php public/data.minify.json
  deploy:
    name: Deploy to repo
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout Code
        uses: actions/checkout@master
      - name: Download Rules Artifacts
        uses: actions/download-artifact@v4
        with:
          name: rules-artifact
          path: public
      - name: Copy files to result
        run: |
          mkdir -p result
          cp public/data.min.json result/data.min.json
          cp public/rules.min.hash result/rules.min.hash
          cp public/data.minify.json result/data.minify.json
          cp public/rules.minify.hash result/rules.minify.hash
      - name: Commit and push result
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add result/
          git commit -m "Update result files [skip ci]" || echo "No changes to commit"
          git push
